# Attention: if you submit an improvement for a Namecoin Cirrus config, please
# file a GitHub issue about it at the namecoin/meta repo, so that we can make
# sure it propagates to all the other Namecoin repos.  Thanks!

task:
  name: Lint
  container:
    image: fedora:latest
    cpu: 1
    memory: 1G
  lint_script:
    ./testdata/lint.sh

# TODO: Maybe cross-compile for Win32 targets too?
task:
  name: Cross-Compile $DISTRO
  matrix:
    - container:
        image: fedora:latest
        cpu: 1
        memory: 1G
      install_script:
        - dnf install -y golang make mingw32-nsis unzip wget
      env:
        DISTRO: Fedora
        NCDNS_LOGGING: "1"
    - container:
        image: debian:latest
        cpu: 1
        memory: 1G
      install_script:
        - apt-get update
        - apt-get install -y curl git golang make nsis unzip wget
      env:
        DISTRO: Debian
  # TODO: fetch latest versions of everything
  fetch_script:
    # TODO: remove this, download a binary of qexe instead
    - go get -d -v github.com/miekg/exdns/q
    # TODO: remove this, download ConsensusJ-Namecoin, certinject, and Encaya like we do everything else.
    - mkdir -p build64/artifacts/
    - cd build64/artifacts/
    - curl -o bitcoinj-daemon.jar https://www.namecoin.org/files/ConsensusJ-Namecoin/0.3.2.1/namecoinj-daemon-0.3.2-SNAPSHOT.jar
    - curl -o certinject--windows_amd64.tar.gz https://api.cirrus-ci.com/v1/artifact/github/namecoin/certinject/Cross-Compile%20Go%20latest/binaries/dist/certinject--windows_amd64.tar.gz
    - tar -xaf certinject--windows_amd64.tar.gz
    - mv certinject--windows_amd64/bin/certinject.exe ./
    - rm -rf certinject--windows_amd64/
    - curl -o encaya--windows_amd64.tar.gz https://api.cirrus-ci.com/v1/artifact/github/namecoin/encaya/Cross-Compile%20Go%20latest/binaries/dist/encaya--windows_amd64.tar.gz
    - tar -xaf encaya--windows_amd64.tar.gz
    - mv encaya--windows_amd64/bin/*.exe ./
    - rm -rf encaya--windows_amd64/
    - cd ../../
  build_script:
    # TODO: check for NSIS warnings
    - make NCDNS_64BIT=1 NCDNS_PRODVER=v0.1.2
    - mv build64/bin/ncdns-*-win64-install.exe ./ncdns--win64-install.exe
  upload_script:
    - curl -s -X POST --data-binary @ncdns--win64-install.exe http://$CIRRUS_HTTP_CACHE_HOST/cross_compile_bin_$DISTRO
  binaries_artifacts:
    path: "ncdns--win64-install.exe"

task:
  name: Installation Tests $BUILD_DISTRO
  windows_container:
    image: cirrusci/windowsservercore:2019
    # Don't use minimal CPU/memory since Namecoin Core may eat some.
  matrix:
    - env:
        INSTALL_VCPP: "0"
    - env:
        INSTALL_VCPP: "1"
      vcpp_script:
        - choco install -y vcredist140
  install_script:
    - curl -o ncdns--win64-install.exe http://%CIRRUS_HTTP_CACHE_HOST%/cross_compile_bin_%BUILD_DISTRO%
    - SET PATH=%PATH%;%cd%
    - powershell -ExecutionPolicy Unrestricted -File "testdata/install.ps1"
  matrix:
    - env:
        BUILD_DISTRO: Fedora
      depends_on:
        - "Cross-Compile Fedora"
    - env:
        BUILD_DISTRO: Debian
      depends_on:
        - "Cross-Compile Debian"

# TODO: GitHub Release Upload

# TODO: Add Windows unit tests

# TODO: "Testing config parsing" from travis.bash

# TODO: Add multiple Go versions to Gox builds and unit tests

# TODO: Add debug stripping and path stripping to Gox for repro builds

# TODO: Re-add darwin/386 for old Go versions where it was supported

# TODO: Fix upload repo for tagged commits (don't use Nightly repo for this)

# TODO: Skip Signify and Release if it's not applicable

# TODO: Signify Nightlies

# TODO: IRC notifications on failure

# TODO: Cron
