@echo off
rem Script installed by ncdns NSIS installer.
rem Workaround for the fact that Unbound on Windows doesn't support globbing include directives.
rem Run this script to regenerate confd-list.conf, based on the contents of unbound.conf.d.
rem It is always safe to run this script.
echo %~dp0

echo # Autogenerated file. > "%~dp0confd-list.conf"
for %%f in ("%~dp0unbound.conf.d\*.conf") do (
  echo include: "%%f" >> "%~dp0confd-list.conf"
)
